/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BancaRouteImport } from './routes/banca'
import { Route as CasaRouteImport } from './routes/casa'
import { Route as CedoliniRouteImport } from './routes/cedolini'
import { Route as FisseRouteImport } from './routes/fisse'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as InvestiRouteImport } from './routes/investi'
import { Route as PatrimonioRouteImport } from './routes/patrimonio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BancaRoute = BancaRouteImport.update({
  id: '/banca',
  path: '/banca',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaRoute = CasaRouteImport.update({
  id: '/casa',
  path: '/casa',
  getParentRoute: () => rootRouteImport,
} as any)
const CedoliniRoute = CedoliniRouteImport.update({
  id: '/cedolini',
  path: '/cedolini',
  getParentRoute: () => rootRouteImport,
} as any)
const FisseRoute = FisseRouteImport.update({
  id: '/fisse',
  path: '/fisse',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestiRoute = InvestiRouteImport.update({
  id: '/investi',
  path: '/investi',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioRoute = PatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banca': typeof BancaRoute
  '/casa': typeof CasaRoute
  '/cedolini': typeof CedoliniRoute
  '/fisse': typeof FisseRoute
  '/glossario': typeof GlossarioRoute
  '/investi': typeof InvestiRoute
  '/patrimonio': typeof PatrimonioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banca': typeof BancaRoute
  '/casa': typeof CasaRoute
  '/cedolini': typeof CedoliniRoute
  '/fisse': typeof FisseRoute
  '/glossario': typeof GlossarioRoute
  '/investi': typeof InvestiRoute
  '/patrimonio': typeof PatrimonioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banca': typeof BancaRoute
  '/casa': typeof CasaRoute
  '/cedolini': typeof CedoliniRoute
  '/fisse': typeof FisseRoute
  '/glossario': typeof GlossarioRoute
  '/investi': typeof InvestiRoute
  '/patrimonio': typeof PatrimonioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banca'
    | '/casa'
    | '/cedolini'
    | '/fisse'
    | '/glossario'
    | '/investi'
    | '/patrimonio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banca'
    | '/casa'
    | '/cedolini'
    | '/fisse'
    | '/glossario'
    | '/investi'
    | '/patrimonio'
  id:
    | '__root__'
    | '/'
    | '/banca'
    | '/casa'
    | '/cedolini'
    | '/fisse'
    | '/glossario'
    | '/investi'
    | '/patrimonio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BancaRoute: typeof BancaRoute
  CasaRoute: typeof CasaRoute
  CedoliniRoute: typeof CedoliniRoute
  FisseRoute: typeof FisseRoute
  GlossarioRoute: typeof GlossarioRoute
  InvestiRoute: typeof InvestiRoute
  PatrimonioRoute: typeof PatrimonioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banca': {
      id: '/banca'
      path: '/banca'
      fullPath: '/banca'
      preLoaderRoute: typeof BancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa': {
      id: '/casa'
      path: '/casa'
      fullPath: '/casa'
      preLoaderRoute: typeof CasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cedolini': {
      id: '/cedolini'
      path: '/cedolini'
      fullPath: '/cedolini'
      preLoaderRoute: typeof CedoliniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fisse': {
      id: '/fisse'
      path: '/fisse'
      fullPath: '/fisse'
      preLoaderRoute: typeof FisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investi': {
      id: '/investi'
      path: '/investi'
      fullPath: '/investi'
      preLoaderRoute: typeof InvestiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio': {
      id: '/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof PatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BancaRoute: BancaRoute,
  CasaRoute: CasaRoute,
  CedoliniRoute: CedoliniRoute,
  FisseRoute: FisseRoute,
  GlossarioRoute: GlossarioRoute,
  InvestiRoute: InvestiRoute,
  PatrimonioRoute: PatrimonioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
